config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get :get_regions, to: 'home#get_regions'
  get :get_lqs, to: 'home#get_lqs'
  get :get_houses, to: 'home#get_houses'

  resources :houses
  resources :lqs
  resources :streets
  resources :cities
  resources :appartments

  get :get_lqs_by_city_region, to: 'appartments#get_lqs_by_city_region'
  get :get_houses_by_lq, to: 'appartments#get_houses_by_lq'
  get :get_street_address, to: 'appartments#get_street_address'
  
  get 'main/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appartment.rb
class Appartment < ActiveRecord::Base
  belongs_to :city
  belongs_to :street
  belongs_to :user
  belongs_to :lq
  belongs_to :house
  belongs_to :city_region
  belongs_to :building_class
  belongs_to :building_type
  belongs_to :construction_phase
  belongs_to :deal_type
  belongs_to :electric_type
  belongs_to :garbage_type
  belongs_to :gas_type
  belongs_to :heating_type
  belongs_to :property_type
  belongs_to :repair_type
  belongs_to :room_type
  belongs_to :sewage_type
  belongs_to :traffic_object
  belongs_to :water_type
  belongs_to :windows_type
  belongs_to :building_state


  has_and_belongs_to_many :goods_types,
                          :class_name => 'GoodsType',
                          :join_table => 'appartment_goods_types',
                          :foreign_key => 'appartment_id',
                          :association_foreign_key => 'goods_type_id'  
  has_and_belongs_to_many :infrastructure_objects,
                          :class_name => 'InfrastructureObject',
                          :join_table => 'appartment_infrastructure_objects',
                          :foreign_key => 'appartment_id',
                          :association_foreign_key => 'infrastructure_object_id'
  has_and_belongs_to_many :parkings,
                          :class_name => 'Parking',
                          :join_table => 'appartment_parkings',
                          :foreign_key => 'appartment_id',
                          :association_foreign_key => 'parking_id'
  has_and_belongs_to_many :security_types,
                          :class_name => 'SecurityType',
                          :join_table => 'appartment_security_types',
                          :foreign_key => 'appartment_id',
                          :association_foreign_key => 'security_type_id'
  has_and_belongs_to_many :territory_objects,
                          :class_name => 'TerritoryObject',
                          :join_table => 'appartment_territory_objects',
                          :foreign_key => 'appartment_id',
                          :association_foreign_key => 'territory_object_id'


end

app/models/city_region.rb
class CityRegion < ActiveRecord::Base
  belongs_to :city
  has_many :appartments
  has_many :lqs

  validates :name, presence: true
end

app/models/deal_type.rb
class DealType < ActiveRecord::Base
end

app/models/garbage_type.rb
class GarbageType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/models/gas_type.rb
class GasType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/models/goods_type.rb
class GoodsType < ActiveRecord::Base
  has_and_belongs_to_many :appartments,
                          :class_name => 'Appartment',
                          :join_table => 'appartment_goods_types',
                          :foreign_key => 'goods_type_id',
                          :association_foreign_key => 'appartment_id'

  validates :name, presence: true
end

app/models/heating_type.rb
class HeatingType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :appartments
  belongs_to :street
  belongs_to :lq

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{self.street.city.name}, #{self.lq.number_code}/#{self.number_lq}"
  end
end

app/models/lq.rb
class Lq < ActiveRecord::Base

  belongs_to :city
  belongs_to :city_region
  has_many :houses

  validates :number_code, presence: true
  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{self.city.name}, #{self.number_code}/1"
  end

  

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  has_and_belongs_to_many :appartments,
                          :class_name => 'Appartment',
                          :join_table => 'appartment_parkings',
                          :foreign_key => 'parking_id',
                          :association_foreign_key => 'appartment_id'

  validates :name, presence: true
end

app/models/repair_type.rb
class RepairType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/models/sewage_type.rb
class SewageType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/models/street.rb
class Street < ActiveRecord::Base

  belongs_to :city
  has_many :houses

  validates :name, presence: true
  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{self.city.name}, #{self.name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :appartments
end

app/models/water_type.rb
class WaterType < ActiveRecord::Base
  has_many :appartments

  validates :name, presence: true
end

app/controllers/appartments_controller.rb
class AppartmentsController < InheritedResources::Base
  before_filter :set_appartments_hash , :only => [:index]

  def get_lqs_by_city_region
    city_region = CityRegion.find(params[:city_region_id])
    options = []
    city_region.lqs.each do |lq|
      options << "<option data-lat='#{lq.latitude}' data-lng='#{lq.longitude}' value='#{lq.id}'>#{lq.number_code}</option>"
    end 
    render :json => options 
  end

  def get_houses_by_lq
    lq = Lq.find(params[:lq_id])
    options = []
    lq.houses.each do |h|
      options << "<option data-lat='#{h.latitude}' data-lng='#{h.longitude}' value='#{h.id}'>#{h.number_lq}</option>"
    end 
    render :json => options 
  end

  def get_street_address
    house = House.find(params[:house_id])
    render :text => "#{house.street.name} - #{house.number_street}" 
  end

  private

    def appartment_params
      params.require(:appartment).permit(:user_id, :city_id, :street_id, :lq_id, :house_id, :latitude, :longitude)
    end

    def set_appartments_hash
      @apps = Appartment.all
      @hash = Gmaps4rails.build_markers(@apps) do |appartment, marker|
        marker.lat appartment.latitude
        marker.lng appartment.longitude
      end
    end
end

app/helpers/appartments_helper.rb
module AppartmentsHelper
  def get_streets_name
     Street.uniq.pluck(:name)    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lqs_helper.rb
module LqsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/appartments/_form.html.slim
= simple_form_for(@appartment) do |f|
  = f.error_notification

  .form-inputs
    .panel.panel-default
      .panel-heading
        h3.panel-title Расположение
      .panel-body
        .row
          .col-md-6
            = f.association :deal_type, input_html: { class: 'select_2' }
            = f.association :city, input_html: { class: 'select_2' }
            .row
              .col-md-6
                = f.association :city_region
              .col-md-6
                .form-group.select.optional.appartment_lq
                  label.select.optional.control-label Комплекс
                  = f.association :lq do
                    = f.select :lq_id, Lq.all.map{ |l| [l.number_code, l.id, { 'data-lat' => l.latitude, 'data-lng' => l.longitude } ] }
            .row          
              .col-md-4
                .form-group.select.optional.appartment_house
                  label.select.optional.control-label Дом
                  = f.association :house do
                    = f.select :house_id, House.all.map{ |h| [h.number_lq, h.id, { 'data-lat' => h.latitude, 'data-lng' => h.longitude } ] }
              .col-md-4
                = f.input :c_number
              .col-md-4
                h5#street
            .col-md-6
              = f.association :traffic_object, input_html: { class: 'select_2' }
            .col-md-6
              = f.input :traffic_object_distance
            = f.input :latitude
            = f.input :longitude
          .col-md-6
            h4 Укажите местоположение объекта на карте
            div style=("width:100%;")
              #map style=("width:100%; height:500px;")
    .panel.panel-default
      .panel-heading
        h3.panel-title Квартира
      .panel-body
        .row
          .col-md-6
            = f.input :lq_name
            = f.input :is_new
          .col-md-6
            = f.input :builder
        .row
          .col-md-6
            = f.association :construction_phase, input_html: { class: 'select_2' }
            
          .col-md-6
            .col-md-8
              = f.input :finish_date_quartal
            .col-md-4
              = f.input :finish_date_year
            = f.input :finished_at, as: :date
        .row
          .col-md-6
            = f.input :is_flat
            = f.input :is_flatpart
            = f.input :is_studio
            = f.input :is_freeplan
            = f.input :is_smallfamily
            = f.input :room_count
            .col-md-4
              = f.input :square
            .col-md-4
              = f.input :living_area
            .col-md-4
              = f.input :kitchen_area
            = f.input :room_area
            = f.input :flat_level
            = f.input :room_height
            = f.association :repair_type, input_html: { class: 'select_2' }
          .col-md-6
            = f.input :floor
            = f.input :total_floor
            = f.association :room_type, input_html: { class: 'select_2' }
            = f.association :property_type, input_html: { class: 'select_2' }
            = f.association :windows_type, input_html: { class: 'select_2' }
    .panel.panel-default
      .panel-heading
        h3.panel-title Что есть?
      .panel-body
        .col-md-6
          = f.input :loggia
          = f.input :loggia_area
          = f.input :loggia_window
          = f.input :balcony
          = f.input :balcony_area
          = f.input :balcony_window
          = f.input :pantry
          = f.input :pantry_area
          = f.input :sauna
          = f.input :pool
          = f.input :pool_area
          = f.input :wc_fused
          = f.input :separate_bathroom
        .col-md-6
          = f.association :goods_types, as: :check_boxes
          = f.association :security_types, as: :check_boxes
    .panel.panel-default
      .panel-heading
        h3.panel-title Дом
      .panel-body
        .col-md-6
          = f.association :building_class, input_html: { class: 'select_2' }
          = f.input :architectural_style
          = f.association :building_type, input_html: { class: 'select_2' }
          = f.association :building_state, input_html: { class: 'select_2' }
          = f.input :elevator
          = f.input :service_elevator
        .col-md-6
          = f.association :gas_type, input_html: { class: 'select_2' }
          = f.association :electric_type, input_html: { class: 'select_2' }
          = f.association :heating_type, input_html: { class: 'select_2' }
          = f.association :water_type, input_html: { class: 'select_2' }
          = f.association :sewage_type, input_html: { class: 'select_2' }
          = f.association :garbage_type, input_html: { class: 'select_2' }
    .panel.panel-default
      .panel-heading
        h3.panel-title Инфраструктура
      .panel-body
        .col-md-4
          = f.association :territory_objects, as: :check_boxes
          = f.input :is_fenced
        .col-md-4
          = f.association :parkings, as: :check_boxes
          = f.input :parking_include
        .col-md-4
          = f.association :infrastructure_objects, as: :check_boxes
    .panel.panel-default
      .panel-heading
        h3.panel-title Сделка
      .panel-body
        .col-md-6
          = f.input :price
          = f.input :is_doc_ready
        .col-md-6
          = f.input :allow_bargaining
          = f.input :allow_brokers
          = f.input :allow_mortgage

    .panel.panel-default
      .panel-heading
        h3.panel-title Временное
      .panel-body

        = f.association :user, input_html: { class: 'select_2' }
  

  .form-actions
    = f.button :submit

app/views/appartments/edit.html.slim
h1 Редактировать квартиру

== render 'form'

= link_to 'Показать', @appartment
'|
= link_to 'Назад', appartments_path

app/views/appartments/index.html.slim
h1 Квартиры
br
= link_to 'Добавить новую', new_appartment_path

.row
  .col-md-6
    - @appartments.each do |appartment|
      .media
        .media-left
          = image_tag("test.jpg", class: "media-object")
        .media-body
          h4.media-heading= "#{appartment.lq.number_code}/#{appartment.house.number_lq} - #{appartment.try(:c_number)}"
          para= appartment.deal_type.try(:name)
          para "Квартира очень светлая, уютная, чистая с евроремонтом (ремонту 5 лет) и перепланировкой (документ на разрешение имеется). на полу везде ламинат"
          .row
            .col-md-3
              = link_to 'Показать', appartment
            .col-md-5
              = link_to 'Редактировать', edit_appartment_path(appartment)
            .col-md-4
              = link_to 'Удалить', appartment, data: {:confirm => 'Вы уверены?'}, :method => :delete

  .col-md-6
    div style=("width:100%;")
      #map style=("width:100%; height:700px;")

#all-apps{data={:list => @hash.to_json}}

app/views/appartments/new.html.slim
h1 Новая квартира

== render 'form'

= link_to 'Назад', appartments_path

app/views/appartments/show.html.slim
p#notice = notice

p
  strong Пользователь:
  = @appartment.user_id
p
  strong Город:
  = @appartment.city.name
p
  strong Улица:
  = @appartment.house.street.name
p
  strong Комплекс:
  = @appartment.lq_id
p
  strong Дом по улице:
  = @appartment.house.number_street
p
  strong Дом по комплексу:
  = @appartment.house.number_lq

= link_to 'Редактировать', edit_appartment_path(@appartment)
'|
= link_to 'Назад', appartments_path